apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubewire
  namespace: vpn
spec:
  template:
    metadata:
      labels:
        app: kubewire
    spec:
      containers:
      - image: antoniaklja/kubewire:latest
        name: kubewire
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 5182 # network tunnel
          protocol: UDP
        - containerPort: 80 # web ui
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 150Mi