kind: Service
metadata:
  name: kubewire-vpn
  namespace: vpn
  labels:
    app: kubewire
spec:
  type: NodePort
  ports:
  - port: 5182
    protocol: UDP
    nodePort: 32367
  selector:
    name: kubewire